/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * read an asset
         * @description Read an asset from the game at the specified path, converting it into a usable format. If no valid conversion between the game file type and specified format exists, an error will be returned.
         */
        get: {
            parameters: {
                query: {
                    /** @description Game version to utilise for this query. */
                    version?: string | null;
                    /** @description Game path of the asset to retrieve. */
                    path: string;
                    /** @description Format that the asset should be converted into. */
                    format: components["schemas"]["SchemaFormat"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description byte stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": unknown;
                        "image/png": unknown;
                        "image/webp": unknown;
                    };
                };
                /** @description not modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description failed operation */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 400,
                         *       "message": "invalid request: example error response"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset/map/{territory}/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * compose a map
         * @description Retrieve the specified map, composing it from split source files if necessary.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Game version to utilise for this query. */
                    version?: string | null;
                };
                header?: never;
                path: {
                    /** @description Territory of the map to be retrieved. This typically takes the form of 4 characters, [letter][number][letter][number]. See `Map`'s `Id` field for examples of possible combinations of `territory` and `index`. */
                    territory: string;
                    /** @description Index of the map within the territory. This invariably takes the form of a two-digit zero-padded number. See `Map`'s `Id` field for examples of possible combinations of `territory` and `index`. */
                    index: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description byte stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": unknown;
                    };
                };
                /** @description not modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description failed operation */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 400,
                         *       "message": "invalid request: example error response"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * execute a search query
         * @description Fetch information about rows and their related data that match the provided search query.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Game version to utilise for this query. */
                    version?: string | null;
                    /** @description Search query to execute in this request. Must be specified if not querying a cursor. URL special characters, such as `+`, must be escaped to prevent mis-parses of the query. */
                    query?: components["schemas"]["QueryString"] | null;
                    /** @description List of excel sheets that the query should be run against. At least one must be specified if not querying a cursor. */
                    sheets?: string | null;
                    /** @description Continuation token to retrieve further results from a prior search request. If specified, takes priority over `query`. */
                    cursor?: string | null;
                    /** @description Maximum number of rows to return. To paginate, provide the cursor token provided in `next` to the `cursor` parameter. */
                    limit?: number | null;
                    /** @description Language to use for data with no language otherwise specified in the fields filter. */
                    language?: components["schemas"]["SchemaLanguage"] | null;
                    /** @description Schema that row data should be read with. */
                    schema?: components["schemas"]["SchemaSpecifier"] | null;
                    /** @description Data fields to read for selected rows. */
                    fields?: components["schemas"]["FilterString"] | null;
                    /** @description Data fields to read for selected rows' transient row, if any is present. */
                    transient?: components["schemas"]["FilterString"] | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "next": "bbe61a5e-7d22-41ec-9f5a-711c967c5624",
                         *       "results": [
                         *         {
                         *           "fields": {
                         *             "FieldName": 14
                         *           },
                         *           "row_id": 1,
                         *           "score": 1.4129999876022339,
                         *           "sheet": "SheetName"
                         *         }
                         *       ],
                         *       "schema": "source@version",
                         *       "version": "f815390159effefd"
                         *     }
                         */
                        "application/json": components["schemas"]["SearchResponse"];
                    };
                };
                /** @description failed operation */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 400,
                         *       "message": "invalid request: example error response"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * list sheets
         * @description List known excel sheets that can be read by the API.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Game version to utilise for this query. */
                    version?: string | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "sheets": [
                         *         {
                         *           "name": "Action"
                         *         },
                         *         {
                         *           "name": "Item"
                         *         },
                         *         {
                         *           "name": "Status"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["ListResponse"];
                    };
                };
                /** @description failed operation */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 400,
                         *       "message": "invalid request: example error response"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheet/{sheet}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * list rows in a sheet
         * @description Read information about one or more rows and their related data.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Rows to fetch from the sheet, as a comma-separated list. Behavior is undefined if both `rows` and `after` are provided. */
                    rows?: string;
                    /** @description Maximum number of rows to return. To paginate, provide the last returned row to the next request's `after` parameter. */
                    limit?: number | null;
                    /** @description Fetch rows after the specified row. Behavior is undefined if both `rows` and `after` are provided. */
                    after?: components["schemas"]["RowSpecifier"] | null;
                    /** @description Language to use for data with no language otherwise specified in the fields filter. */
                    language?: components["schemas"]["SchemaLanguage"] | null;
                    /** @description Schema that row data should be read with. */
                    schema?: components["schemas"]["SchemaSpecifier"] | null;
                    /** @description Data fields to read for selected rows. */
                    fields?: components["schemas"]["FilterString"] | null;
                    /** @description Data fields to read for selected rows' transient row, if any is present. */
                    transient?: components["schemas"]["FilterString"] | null;
                };
                header?: never;
                path: {
                    /** @description Name of the sheet to read. */
                    sheet: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "rows": [
                         *         {
                         *           "fields": {
                         *             "FieldName": 14
                         *           },
                         *           "row_id": 1
                         *         },
                         *         {
                         *           "fields": {
                         *             "FieldName": 14
                         *           },
                         *           "row_id": 2
                         *         }
                         *       ],
                         *       "schema": "source@version",
                         *       "version": "f815390159effefd"
                         *     }
                         */
                        "application/json": components["schemas"]["SheetResponse"];
                    };
                };
                /** @description failed operation */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 400,
                         *       "message": "invalid request: example error response"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sheet/{sheet}/{row}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * read a sheet row
         * @description Read detailed, filterable information from a single sheet row and its related data.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Language to use for data with no language otherwise specified in the fields filter. */
                    language?: components["schemas"]["SchemaLanguage"] | null;
                    /** @description Schema that row data should be read with. */
                    schema?: components["schemas"]["SchemaSpecifier"] | null;
                    /** @description Data fields to read for selected rows. */
                    fields?: components["schemas"]["FilterString"] | null;
                    /** @description Data fields to read for selected rows' transient row, if any is present. */
                    transient?: components["schemas"]["FilterString"] | null;
                };
                header?: never;
                path: {
                    /** @description Name of the sheet to read. */
                    sheet: string;
                    /** @description Row to read. */
                    row: components["schemas"]["RowSpecifier"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "fields": {
                         *         "FieldName": 14
                         *       },
                         *       "row_id": 1,
                         *       "schema": "source@version",
                         *       "version": "f815390159effefd"
                         *     }
                         */
                        "application/json": components["schemas"]["RowResponse"];
                    };
                };
                /** @description failed operation */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "code": 400,
                         *       "message": "invalid request: example error response"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * list versions
         * @description List versions understood by the API.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "versions": [
                         *         {
                         *           "key": "f815390159effefd",
                         *           "names": [
                         *             "7.0"
                         *           ]
                         *         },
                         *         {
                         *           "key": "2139246928a48a9a",
                         *           "names": [
                         *             "7.01",
                         *             "latest"
                         *           ]
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["VersionsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Query parameters accepted by the asset endpoint. */
        AssetQuery: {
            /**
             * @description Format that the asset should be converted into.
             * @example png
             */
            format: components["schemas"]["SchemaFormat"];
            /**
             * @description Game path of the asset to retrieve.
             * @example ui/icon/051000/051474_hr1.tex
             */
            path: string;
        };
        /** @description General purpose error response structure. */
        ErrorResponse: {
            /** @description HTTP status code of the error. Will match the server response code. */
            code: components["schemas"]["StatusCode"];
            /** @description Description of what went wrong. */
            message: string;
        };
        /**
         * @description A filter string for selecting fields within a row.
         *
         *     Filters are comprised of a comma-seperated list of field paths, i.e. `a,b` will select the fields `a` and `b`.
         *
         *     Decorators may be used to modify the way a field is read. They take the form of `@decorator(arguments)`, i.e. `field@lang(en)`. Currently accepted decorators:
         *
         *     - `@lang(<language>)`: Overrides the query's language for the decorated field. Allows one query to access data for multiple languages. `language` accepts any valid `LanguageString`.
         *
         *     - `@as(<format>)`: Overrides the default output format for the decorated field.
         *
         *     Currently accepted `format`s for `@as`:
         *
         *     - `raw`: Prevents further processing, such as sheet relations, being performed on the decorated field. Has no effect on regular scalar fields.
         *
         *     - `html`: Formats a string field as rich HTML. Invalid on non-string fields. Output will be a valid HTML fragment, however no stability guarantees are made over the precise markup used.
         *
         *     Nested fields may be selected using dot notation, i.e. `a.b` will select the field `b` contained in the struct `a`.
         *
         *     Arrays must be targeted if selecting fields within them, i.e. `a[].b` will select _all_ `b` fields of structs within the array `a`, however `a.b` will select nothing.
         */
        FilterString: string;
        /** @description Response structure for the list endpoint. */
        ListResponse: {
            /** @description Array of sheets known to the API. */
            sheets: components["schemas"]["SheetMetadata"][];
        };
        /** @description Path segments expected by the asset map endpoint. */
        MapPath: {
            /**
             * @description Index of the map within the territory. This invariably takes the form of a two-digit zero-padded number. See `Map`'s `Id` field for examples of possible combinations of `territory` and `index`.
             * @example 00
             */
            index: string;
            /**
             * @description Territory of the map to be retrieved. This typically takes the form of 4 characters, [letter][number][letter][number]. See `Map`'s `Id` field for examples of possible combinations of `territory` and `index`.
             * @example s1d1
             */
            territory: string;
        };
        /**
         * @description A query string for searching excel data.
         *
         *     Queries are formed of clauses, which take the basic form of `[specifier][operation][value]`, i.e. `Name="Example"`. Multiple clauses may be specified by seperating them with whitespace, i.e. `Foo=1 Bar=2`.
         *
         *     Like field filters, clause specifiers may use dot notation to specify fields inside structs and relations (i.e. `Foo.Bar=1)`, as well as language tags to target fields in particular languages (i.e. `Foo@ja=1`).
         *
         *     Arrays must be selected explicitly (i.e. `Foo[]=1`), resulting in a match for any value within the array. An index can be used to reduce the search space (i.e. `Foo[1]=1`).
         *
         *     By default, results will match at least one clause, with higher relevance scores for those that match more. To modify this behavior, clauses can decorated. `+clause` specifies that the clause _must_ be matched for any result returned, and `-clause` specifies that it _must not_ be matched.
         *
         *     To represent more involved boolean matching, clauses may be grouped with parentheses. `+(a b) +c` will require that either clauses a _or_ b must match, in addition to c matching.
         *
         *     Supported operations:
         *
         *     - partial string match: `key~"value"`
         *
         *     - exact equality: `key=value`
         *
         *     - numeric comparison: `key>=value`, `key>value`, `key<=value`, `key<value`
         *
         *     Supported value types:
         *
         *     - string: `"example"`
         *
         *     - number: `1`, `-1`, `1.0`
         *
         *     - boolean: `true`, `false`
         */
        QueryString: string;
        /** @description Path variables accepted by the row endpoint. */
        RowPath: {
            /** @description Row to read. */
            row: components["schemas"]["RowSpecifier"];
            /** @description Name of the sheet to read. */
            sheet: string;
        };
        /** @description Query parameters accepted by endpoints that retrieve excel row data. */
        RowReaderQuery: {
            /** @description Data fields to read for selected rows. */
            fields?: components["schemas"]["FilterString"] | null;
            /** @description Language to use for data with no language otherwise specified in the fields filter. */
            language?: components["schemas"]["SchemaLanguage"] | null;
            /** @description Schema that row data should be read with. */
            schema?: components["schemas"]["SchemaSpecifier"] | null;
            /** @description Data fields to read for selected rows' transient row, if any is present. */
            transient?: components["schemas"]["FilterString"] | null;
        };
        /** @description Response structure for the row endpoint. */
        RowResponse: {
            /** @description Field values for this row, according to the current schema and field filter. */
            fields: components["schemas"]["ValueString"];
            /**
             * Format: uint32
             * @description ID of this row.
             */
            row_id: number;
            /** @description The canonical specifier for the schema used in this response. */
            schema: string;
            /**
             * Format: uint16
             * @description Subrow ID of this row, when relevant.
             */
            subrow_id?: number | null;
            /** @description Field values for this row's transient row, if any is present, according to the current schema and transient filter. */
            transient?: components["schemas"]["ValueString"] | null;
            /** @description The canonical specifier for the version used in this response. */
            version: string;
        };
        RowResult: {
            /** @description Field values for this row, according to the current schema and field filter. */
            fields: components["schemas"]["ValueString"];
            /**
             * Format: uint32
             * @description ID of this row.
             */
            row_id: number;
            /**
             * Format: uint16
             * @description Subrow ID of this row, when relevant.
             */
            subrow_id?: number | null;
            /** @description Field values for this row's transient row, if any is present, according to the current schema and transient filter. */
            transient?: components["schemas"]["ValueString"] | null;
        };
        RowSpecifier: string;
        /** @enum {string} */
        SchemaFormat: "jpg" | "png" | "webp";
        /**
         * @description Known languages supported by the game data format. **NOTE:** Not all languages that are supported by the format are valid for all editions of the game. For example, the global game client acknowledges the existence of `chs` and `kr`, however does not provide any data for them.
         * @enum {string}
         */
        SchemaLanguage: "none" | "ja" | "en" | "de" | "fr" | "chs" | "cht" | "kr";
        SchemaSpecifier: string;
        /** @description Query paramters accepted by the search endpoint. */
        SearchQuery: {
            /**
             * Format: uuid
             * @description Continuation token to retrieve further results from a prior search request. If specified, takes priority over `query`.
             */
            cursor?: string | null;
            /**
             * Format: uint
             * @description Maximum number of rows to return. To paginate, provide the cursor token provided in `next` to the `cursor` parameter.
             */
            limit?: number | null;
            /** @description Search query to execute in this request. Must be specified if not querying a cursor. URL special characters, such as `+`, must be escaped to prevent mis-parses of the query. */
            query?: components["schemas"]["QueryString"] | null;
            /** @description List of excel sheets that the query should be run against. At least one must be specified if not querying a cursor. */
            sheets?: string | null;
        };
        /** @description Response structure for the search endpoint. */
        SearchResponse: {
            /**
             * Format: uuid
             * @description A cursor that can be used to retrieve further results if available.
             */
            next?: string | null;
            /** @description Array of results found by the query, sorted by their relevance. */
            results: components["schemas"]["SearchResult"][];
            /** @description The canonical specifier for the schema used in this response. */
            schema: string;
            /** @description The canonical specifier for the version used in this response. */
            version: string;
        };
        /** @description Result found by a search query, hydrated with data from the underlying excel row the result represents. */
        SearchResult: {
            /** @description Field values for this row, according to the current schema and field filter. */
            fields: components["schemas"]["ValueString"];
            /**
             * Format: uint32
             * @description ID of this row.
             */
            row_id: number;
            /**
             * Format: float
             * @description Relevance score for this entry.
             *
             *     These values only loosely represent the relevance of an entry to the search query. No guarantee is given that the discrete values, nor resulting sort order, will remain stable.
             */
            score: number;
            /** @description Excel sheet this result was found in. */
            sheet: string;
            /**
             * Format: uint16
             * @description Subrow ID of this row, when relevant.
             */
            subrow_id?: number | null;
            /** @description Field values for this row's transient row, if any is present, according to the current schema and transient filter. */
            transient?: components["schemas"]["ValueString"] | null;
        };
        /** @description Metadata about a single sheet. */
        SheetMetadata: {
            /** @description The name of the sheet. */
            name: string;
        };
        /** @description Path variables accepted by the sheet endpoint. */
        SheetPath: {
            /** @description Name of the sheet to read. */
            sheet: string;
        };
        /** @description Query parameters accepted by the sheet endpoint. */
        SheetQuery: {
            /** @description Fetch rows after the specified row. Behavior is undefined if both `rows` and `after` are provided. */
            after?: components["schemas"]["RowSpecifier"] | null;
            /**
             * Format: uint
             * @description Maximum number of rows to return. To paginate, provide the last returned row to the next request's `after` parameter.
             */
            limit?: number | null;
            /** @description Rows to fetch from the sheet, as a comma-separated list. Behavior is undefined if both `rows` and `after` are provided. */
            rows?: string;
        };
        /** @description Response structure for the sheet endpoint. */
        SheetResponse: {
            /** @description Array of rows retrieved by the query. */
            rows: components["schemas"]["RowResult"][];
            /** @description The canonical specifier for the schema used in this response. */
            schema: string;
            /** @description The canonical specifier for the version used in this response. */
            version: string;
        };
        /** Format: uint16 */
        StatusCode: number;
        ValueString: Record<string, never>;
        /** @description Metadata about a single version supported by the API. */
        VersionMetadata: {
            /** @description Canonical key for this version. */
            key: string;
            /** @description Names associated with this version. Version names specified here are accepted by the `version` query parameter throughout the API. */
            names: string[];
        };
        /**
         * VersionQuery
         * @description Query parameters accepted by endpoints that interact with versioned game data.
         */
        VersionQueryParams: {
            /** @description Game version to utilise for this query. */
            version?: string | null;
        };
        /** @description Response structure for the version endpoint. */
        VersionsResponse: {
            /** @description Array of versions available in the API. */
            versions: components["schemas"]["VersionMetadata"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
