/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v2/data-centers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Returns all data centers supported by the API. */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V3.Game.DataCenter'][]
            'application/json': components['schemas']['Universalis.Application.Views.V3.Game.DataCenter'][]
            'text/json': components['schemas']['Universalis.Application.Views.V3.Game.DataCenter'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/worlds': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Returns the IDs and names of all worlds supported by the API. */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V3.Game.World'][]
            'application/json': components['schemas']['Universalis.Application.Views.V3.Game.World'][]
            'text/json': components['schemas']['Universalis.Application.Views.V3.Game.World'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/aggregated/{worldDcRegion}/{itemIds}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieves aggregated market board data for the given items.
     *     Up to 100 item IDs can be comma-separated in order to retrieve data for multiple items at once.
     *     AverageSalePrice and DailySaleVelocity are calculated based on sales of the last 4 days.
     *     This API uses only cached values and is therefore strongly preferred over CurrentlyShown if individual sales/listings are not required.
     */
    get: {
      parameters: {
        query?: never
        header?: {
          'User-Agent'?: string
          'CF-Connecting-IP'?: string
        }
        path: {
          /** @description The item ID or comma-separated item IDs to retrieve data for. */
          itemIds: string
          /** @description The world, data center, or region to retrieve data for. This may be an ID or a name. Regions should be specified as Japan, Europe, North-America, Oceania, China, or 中国. */
          worldDcRegion: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Data retrieved successfully. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData']
            'application/json': components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData']
            'text/json': components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData']
          }
        }
        /** @description The parameters were invalid. */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'application/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'text/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
          }
        }
        /**
         * @description The world/DC or item requested is invalid. When requesting multiple items at once, an invalid item ID
         *     will not trigger this. Instead, the returned list of unresolved item IDs will contain the invalid item ID or IDs.
         */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'application/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'text/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/extra/content/{contentId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Returns the content object associated with the provided content ID. Please note that this endpoint is largely untested,
     *     and may return inconsistent data at times.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description The ID of the content object to retrieve. */
          contentId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V1.Extra.ContentView']
            'application/json': components['schemas']['Universalis.Application.Views.V1.Extra.ContentView']
            'text/json': components['schemas']['Universalis.Application.Views.V1.Extra.ContentView']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/extra/stats/least-recently-updated': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the least-recently updated items on the specified world or data center, along with the upload times for each item. */
    get: {
      parameters: {
        query?: {
          /** @description The world to request data for. */
          world?: string
          /** @description The data center to request data for. */
          dcName?: string
          /** @description The number of entries to return (default 50, max 200). */
          entries?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.MostRecentlyUpdatedItemsView']
            'application/json': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.MostRecentlyUpdatedItemsView']
            'text/json': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.MostRecentlyUpdatedItemsView']
          }
        }
        /** @description The world/DC requested is invalid. */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'application/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'text/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/{worldDcRegion}/{itemIds}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieves the data currently shown on the market board for the requested item and world or data center.
     *     Up to 100 item IDs can be comma-separated in order to retrieve data for multiple items at once.
     */
    get: {
      parameters: {
        query?: {
          /** @description The number of listings to return per item. By default, all listings will be returned. */
          listings?: string
          /** @description The number of recent history entries to return per item. By default, a maximum of 5 entries will be returned. */
          entries?: string
          /** @description Filter for HQ listings and entries. By default, both HQ and NQ listings and entries will be returned. */
          hq?: string
          /** @description The amount of time before now to calculate stats over, in milliseconds. By default, this is 7 days. */
          statsWithin?: string
          /** @description The amount of time before now to take entries within, in seconds. Negative values will be ignored. */
          entriesWithin?: string
          /**
           * @description A comma separated list of fields that should be included in the response, if omitted will return all fields.
           *     For example, if you're only interested in the listings price per unit you can set this to listings.pricePerUnit.
           *     Note that querying multiple items changes the response schema, which should be reflected in the value provided
           *     for this field. In this case, querying the price per unit requires setting this field to
           *     items.listings.pricePerUnit.
           */
          fields?: string
        }
        header?: {
          'User-Agent'?: string
          'CF-Connecting-IP'?: string
        }
        path: {
          /** @description The item ID or comma-separated item IDs to retrieve data for. */
          itemIds: string
          /** @description The world, data center, or region to retrieve data for. This may be an ID or a name. Regions should be specified as Japan, Europe, North-America, Oceania, China, or 中国. */
          worldDcRegion: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Data retrieved successfully. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V2.CurrentlyShownMultiViewV2']
            'application/json': components['schemas']['Universalis.Application.Views.V2.CurrentlyShownMultiViewV2']
            'text/json': components['schemas']['Universalis.Application.Views.V2.CurrentlyShownMultiViewV2']
          }
        }
        /** @description The parameters were invalid. */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /**
         * @description The world/DC or item requested is invalid. When requesting multiple items at once, an invalid item ID
         *     will not trigger this. Instead, the returned list of unresolved item IDs will contain the invalid item ID or IDs.
         */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'application/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'text/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/history/{worldDcRegion}/{itemIds}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieves the history data for the requested item and world or data center.
     *     Up to 100 item IDs can be comma-separated in order to retrieve data for multiple items at once.
     */
    get: {
      parameters: {
        query?: {
          /** @description The number of entries to return per item. By default, this is set to 1800, but may be set to a maximum of 99999. */
          entriesToReturn?: string
          /** @description The amount of time before now to calculate stats over, in milliseconds. By default, this is 7 days. */
          statsWithin?: string
          /** @description The amount of time before entriesUntil or now to take entries within, in seconds. Negative values will be ignored. By default, this is 7 days. */
          entriesWithin?: string
          /** @description The UNIX timestamp in seconds to take entries until. Negative values will be ignored. By default, this is current time. */
          entriesUntil?: string
          /** @description The inclusive minimum unit sale price of entries to return. */
          minSalePrice?: number
          /** @description The inclusive maximum unit sale price of entries to return. */
          maxSalePrice?: number
        }
        header?: {
          'User-Agent'?: string
          'CF-Connecting-IP'?: string
        }
        path: {
          /** @description The item ID or comma-separated item IDs to retrieve data for. */
          itemIds: string
          /** @description The world or data center to retrieve data for. This may be an ID or a name. Regions should be specified as Japan, Europe, North-America, Oceania, China, or 中国. */
          worldDcRegion: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Data retrieved successfully. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V2.HistoryMultiViewV2']
            'application/json': components['schemas']['Universalis.Application.Views.V2.HistoryMultiViewV2']
            'text/json': components['schemas']['Universalis.Application.Views.V2.HistoryMultiViewV2']
          }
        }
        /**
         * @description The world/DC or item requested is invalid. When requesting multiple items at once, an invalid item ID
         *     will not trigger this. Instead, the returned list of unresolved item IDs will contain the invalid item ID or IDs.
         */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'application/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'text/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/tax-rates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Retrieves the current tax rate data for the specified world. This data is provided by the Retainer Vocate in each major city. */
    get: {
      parameters: {
        query?: {
          /** @description The world or to retrieve data for. This may be an ID or a name. */
          world?: string
        }
        header?: {
          'User-Agent'?: string
        }
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Data retrieved successfully. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V1.TaxRatesView']
            'application/json': components['schemas']['Universalis.Application.Views.V1.TaxRatesView']
            'text/json': components['schemas']['Universalis.Application.Views.V1.TaxRatesView']
          }
        }
        /** @description The world requested is invalid. */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'application/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'text/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/marketable': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Returns the set of marketable item IDs. */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': number[]
            'application/json': number[]
            'text/json': number[]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/extra/stats/most-recently-updated': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the most-recently updated items on the specified world or data center, along with the upload times for each item. */
    get: {
      parameters: {
        query?: {
          /** @description The world to request data for. */
          world?: string
          /** @description The data center to request data for. */
          dcName?: string
          /** @description The number of entries to return (default 50, max 200). */
          entries?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.MostRecentlyUpdatedItemsView']
            'application/json': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.MostRecentlyUpdatedItemsView']
            'text/json': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.MostRecentlyUpdatedItemsView']
          }
        }
        /** @description The world/DC requested is invalid. */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'application/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'text/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/extra/stats/recently-updated': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Returns a list of some of the most recently updated items on the website. This endpoint
     *     is a legacy endpoint and does not include any data on which worlds or data centers the updates happened on.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.RecentlyUpdatedItemsView']
            'application/json': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.RecentlyUpdatedItemsView']
            'text/json': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.RecentlyUpdatedItemsView']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/extra/stats/uploader-upload-counts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Returns the total upload counts for each client application that uploads data to Universalis. */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.SourceUploadCountView'][]
            'application/json': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.SourceUploadCountView'][]
            'text/json': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.SourceUploadCountView'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/extra/stats/world-upload-counts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Returns the world upload counts and proportions of the total uploads for each world. */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': {
              [
                key: string
              ]: components['schemas']['Universalis.Application.Views.V1.Extra.Stats.WorldUploadCountView']
            }
            'application/json': {
              [
                key: string
              ]: components['schemas']['Universalis.Application.Views.V1.Extra.Stats.WorldUploadCountView']
            }
            'text/json': {
              [
                key: string
              ]: components['schemas']['Universalis.Application.Views.V1.Extra.Stats.WorldUploadCountView']
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/extra/stats/upload-history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Returns the number of uploads per day over the past 30 days. */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.UploadCountHistoryView']
            'application/json': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.UploadCountHistoryView']
            'text/json': components['schemas']['Universalis.Application.Views.V1.Extra.Stats.UploadCountHistoryView']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/lists/{listId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Retrieves a user list. */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description The ID of the list to retrieve. */
          listId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Data retrieved successfully. */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Universalis.Application.Views.V2.UserListView']
            'application/json': components['schemas']['Universalis.Application.Views.V2.UserListView']
            'text/json': components['schemas']['Universalis.Application.Views.V2.UserListView']
          }
        }
        /** @description The list requested does not exist. */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'application/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
            'text/json': components['schemas']['Microsoft.AspNetCore.Mvc.ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/ws': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Connect to the WebSocket endpoint of the API. Requires a valid WebSocket client. */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v2/ws-dev': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Connect to the WebSocket dev endpoint of the API. Requires a valid WebSocket client. */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    'Microsoft.AspNetCore.Mvc.ProblemDetails': {
      type?: string | null
      title?: string | null
      /** Format: int32 */
      status?: number | null
      detail?: string | null
      instance?: string | null
    } & {
      [key: string]: unknown
    }
    'Universalis.Application.Views.V1.CurrentlyShownView': {
      /**
       * Format: int32
       * @description The item ID.
       */
      itemID: number
      /**
       * Format: int32
       * @description The world ID, if applicable.
       */
      worldID?: number | null
      /**
       * Format: int64
       * @description The last upload time for this endpoint, in milliseconds since the UNIX epoch.
       */
      lastUploadTime: number
      /** @description The currently-shown listings. */
      listings?:
        | components['schemas']['Universalis.Application.Views.V1.ListingView'][]
        | null
      /** @description The currently-shown sales. */
      recentHistory?:
        | components['schemas']['Universalis.Application.Views.V1.SaleView'][]
        | null
      /** @description The DC name, if applicable. */
      dcName?: string | null
      /** @description The region name, if applicable. */
      regionName?: string | null
      /**
       * Format: float
       * @description The average listing price.
       */
      currentAveragePrice: number
      /**
       * Format: float
       * @description The average NQ listing price.
       */
      currentAveragePriceNQ: number
      /**
       * Format: float
       * @description The average HQ listing price.
       */
      currentAveragePriceHQ: number
      /**
       * Format: float
       * @description The average number of sales per day, over the past seven days (or the entirety of the shown sales, whichever comes first).
       *     This number will tend to be the same for every item, because the number of shown sales is the same and over the same period.
       *     This statistic is more useful in historical queries.
       */
      regularSaleVelocity: number
      /**
       * Format: float
       * @description The average number of NQ sales per day, over the past seven days (or the entirety of the shown sales, whichever comes first).
       *     This number will tend to be the same for every item, because the number of shown sales is the same and over the same period.
       *     This statistic is more useful in historical queries.
       */
      nqSaleVelocity: number
      /**
       * Format: float
       * @description The average number of HQ sales per day, over the past seven days (or the entirety of the shown sales, whichever comes first).
       *     This number will tend to be the same for every item, because the number of shown sales is the same and over the same period.
       *     This statistic is more useful in historical queries.
       */
      hqSaleVelocity: number
      /**
       * Format: float
       * @description The average sale price.
       */
      averagePrice: number
      /**
       * Format: float
       * @description The average NQ sale price.
       */
      averagePriceNQ: number
      /**
       * Format: float
       * @description The average HQ sale price.
       */
      averagePriceHQ: number
      /**
       * Format: int32
       * @description The minimum listing price.
       */
      minPrice: number
      /**
       * Format: int32
       * @description The minimum NQ listing price.
       */
      minPriceNQ: number
      /**
       * Format: int32
       * @description The minimum HQ listing price.
       */
      minPriceHQ: number
      /**
       * Format: int32
       * @description The maximum listing price.
       */
      maxPrice: number
      /**
       * Format: int32
       * @description The maximum NQ listing price.
       */
      maxPriceNQ: number
      /**
       * Format: int32
       * @description The maximum HQ listing price.
       */
      maxPriceHQ: number
      /** @description A map of quantities to listing counts, representing the number of listings of each quantity. */
      stackSizeHistogram?: {
        [key: string]: number
      } | null
      /** @description A map of quantities to NQ listing counts, representing the number of listings of each quantity. */
      stackSizeHistogramNQ?: {
        [key: string]: number
      } | null
      /** @description A map of quantities to HQ listing counts, representing the number of listings of each quantity. */
      stackSizeHistogramHQ?: {
        [key: string]: number
      } | null
      /** @description The world name, if applicable. */
      worldName?: string | null
      /** @description The last upload times in milliseconds since epoch for each world in the response, if this is a DC request. */
      worldUploadTimes?: {
        [key: string]: number | null
      } | null
      /**
       * Format: int32
       * @description The number of listings retrieved for the request. When using the "listings" limit parameter, this may be
       *     different from the number of sale entries returned in an API response.
       */
      listingsCount: number
      /**
       * Format: int32
       * @description The number of sale entries retrieved for the request. When using the "entries" limit parameter, this may be
       *     different from the number of sale entries returned in an API response.
       */
      recentHistoryCount: number
      /**
       * Format: int32
       * @description The number of items (not listings) up for sale.
       */
      unitsForSale: number
      /**
       * Format: int32
       * @description The number of items (not sale entries) sold over the retrieved sales.
       */
      unitsSold: number
      /** @description Whether this item has ever been updated. Useful for newly-released items. */
      readonly hasData: boolean
    }
    'Universalis.Application.Views.V1.Extra.ContentView': {
      /** @description The content ID of the object. */
      contentID?: string | null
      /** @description The content type of this object. */
      contentType?: string | null
      /** @description The character name associated with this character object, if this is one. */
      characterName?: string | null
    }
    'Universalis.Application.Views.V1.Extra.Stats.MostRecentlyUpdatedItemsView': {
      /** @description A list of item upload information in timestamp-descending order. */
      items?:
        | components['schemas']['Universalis.Application.Views.V1.Extra.Stats.WorldItemRecencyView'][]
        | null
    }
    'Universalis.Application.Views.V1.Extra.Stats.RecentlyUpdatedItemsView': {
      /** @description A list of item IDs, with the most recent first. */
      items?: number[] | null
    }
    'Universalis.Application.Views.V1.Extra.Stats.SourceUploadCountView': {
      /** @description The name of the client application. */
      sourceName?: string | null
      /**
       * Format: double
       * @description The number of uploads originating from the client application.
       */
      uploadCount: number
    }
    'Universalis.Application.Views.V1.Extra.Stats.UploadCountHistoryView': {
      /** @description The list of upload counts per day, over the past 30 days. */
      uploadCountByDay?: number[] | null
    }
    'Universalis.Application.Views.V1.Extra.Stats.WorldItemRecencyView': {
      /**
       * Format: int32
       * @description The item ID.
       */
      itemID: number
      /**
       * Format: double
       * @description The last upload time for the item on the listed world.
       */
      lastUploadTime: number
      /**
       * Format: int32
       * @description The world ID.
       */
      worldID: number
      /** @description The world name. */
      worldName?: string | null
    }
    'Universalis.Application.Views.V1.Extra.Stats.WorldUploadCountView': {
      /**
       * Format: double
       * @description The number of times an upload has occurred on this world.
       */
      count: number
      /**
       * Format: double
       * @description The proportion of uploads on this world to the total number of uploads.
       */
      proportion: number
    }
    'Universalis.Application.Views.V1.HistoryView': {
      /**
       * Format: int32
       * @description The item ID.
       */
      itemID: number
      /**
       * Format: int32
       * @description The world ID, if applicable.
       */
      worldID?: number | null
      /**
       * Format: int64
       * @description The last upload time for this endpoint, in milliseconds since the UNIX epoch.
       */
      lastUploadTime: number
      /** @description The historical sales. */
      entries?:
        | components['schemas']['Universalis.Application.Views.V1.MinimizedSaleView'][]
        | null
      /** @description The DC name, if applicable. */
      dcName?: string | null
      /** @description The region name, if applicable. */
      regionName?: string | null
      /** @description A map of quantities to sale counts, representing the number of sales of each quantity. */
      stackSizeHistogram?: {
        [key: string]: number
      } | null
      /** @description A map of quantities to NQ sale counts, representing the number of sales of each quantity. */
      stackSizeHistogramNQ?: {
        [key: string]: number
      } | null
      /** @description A map of quantities to HQ sale counts, representing the number of sales of each quantity. */
      stackSizeHistogramHQ?: {
        [key: string]: number
      } | null
      /**
       * Format: float
       * @description The average number of sales per day, over the past seven days (or the entirety of the shown sales, whichever comes first).
       */
      regularSaleVelocity: number
      /**
       * Format: float
       * @description The average number of NQ sales per day, over the past seven days (or the entirety of the shown sales, whichever comes first).
       */
      nqSaleVelocity: number
      /**
       * Format: float
       * @description The average number of HQ sales per day, over the past seven days (or the entirety of the shown sales, whichever comes first).
       */
      hqSaleVelocity: number
      /** @description The world name, if applicable. */
      worldName?: string | null
    }
    'Universalis.Application.Views.V1.ListingView': {
      /**
       * Format: int64
       * @description The time that this listing was posted, in seconds since the UNIX epoch.
       */
      lastReviewTime: number
      /**
       * Format: int32
       * @description The price per unit sold.
       */
      pricePerUnit: number
      /**
       * Format: int32
       * @description The stack size sold.
       */
      quantity: number
      /**
       * Format: int32
       * @description The ID of the dye on this item.
       */
      stainID: number
      /** @description The world name, if applicable. */
      worldName?: string | null
      /**
       * Format: int32
       * @description The world ID, if applicable.
       */
      worldID?: number | null
      /** @description The creator's character name. */
      creatorName?: string | null
      /** @description A SHA256 hash of the creator's ID. */
      creatorID?: string | null
      /** @description Whether or not the item is high-quality. */
      hq: boolean
      /** @description Whether or not the item is crafted. */
      isCrafted: boolean
      /** @description The ID of this listing. */
      listingID?: string | null
      /** @description The materia on this item. */
      materia?:
        | components['schemas']['Universalis.Application.Views.V1.MateriaView'][]
        | null
      /** @description Whether or not the item is being sold on a mannequin. */
      onMannequin: boolean
      /**
       * Format: int32
       * @description The city ID of the retainer. This is a game ID; all possible values can be seen at
       *     https://xivapi.com/Town.
       *
       *     Limsa Lominsa = 1
       *     Gridania = 2
       *     Ul'dah = 3
       *     Ishgard = 4
       *     Kugane = 7
       *     Crystarium = 10
       *     Old Sharlayan = 12
       */
      retainerCity: number
      /** @description The retainer's ID. */
      retainerID?: string | null
      /** @description The retainer's name. */
      retainerName?: string | null
      /** @description A SHA256 hash of the seller's ID. */
      sellerID?: string | null
      /**
       * Format: int32
       * @description The total price.
       */
      total: number
      /**
       * Format: int32
       * @description The Gil sales tax (GST) to be added to the total price during purchase.
       */
      tax: number
    }
    'Universalis.Application.Views.V1.MateriaView': {
      /**
       * Format: int32
       * @description The materia slot.
       */
      slotID: number
      /**
       * Format: int32
       * @description The materia item ID.
       */
      materiaID: number
    }
    'Universalis.Application.Views.V1.MinimizedSaleView': {
      /** @description Whether or not the item was high-quality. */
      hq: boolean
      /**
       * Format: int32
       * @description The price per unit sold.
       */
      pricePerUnit: number
      /**
       * Format: int32
       * @description The stack size sold.
       */
      quantity: number
      /** @description The buyer's character name. This may be null. */
      buyerName?: string | null
      /** @description Whether or not this was purchased from a mannequin. This may be null. */
      onMannequin?: boolean | null
      /**
       * Format: int64
       * @description The sale time, in seconds since the UNIX epoch.
       */
      timestamp: number
      /** @description The world name, if applicable. */
      worldName?: string | null
      /**
       * Format: int32
       * @description The world ID, if applicable.
       */
      worldID?: number | null
    }
    'Universalis.Application.Views.V1.SaleView': {
      /** @description Whether or not the item was high-quality. */
      hq: boolean
      /**
       * Format: int32
       * @description The price per unit sold.
       */
      pricePerUnit: number
      /**
       * Format: int32
       * @description The stack size sold.
       */
      quantity: number
      /**
       * Format: int64
       * @description The sale time, in seconds since the UNIX epoch.
       */
      timestamp: number
      /** @description Whether or not this was purchased from a mannequin. This may be null. */
      onMannequin?: boolean | null
      /** @description The world name, if applicable. */
      worldName?: string | null
      /**
       * Format: int32
       * @description The world ID, if applicable.
       */
      worldID?: number | null
      /** @description The buyer name. */
      buyerName?: string | null
      /**
       * Format: int32
       * @description The total price.
       */
      total: number
    }
    'Universalis.Application.Views.V1.TaxRatesView': {
      /**
       * Format: int32
       * @description The percent retainer tax in Limsa Lominsa.
       */
      'Limsa Lominsa': number
      /**
       * Format: int32
       * @description The percent retainer tax in Gridania.
       */
      Gridania: number
      /**
       * Format: int32
       * @description The percent retainer tax in Ul'dah.
       */
      "Ul'dah": number
      /**
       * Format: int32
       * @description The percent retainer tax in Ishgard.
       */
      Ishgard: number
      /**
       * Format: int32
       * @description The percent retainer tax in Kugane.
       */
      Kugane: number
      /**
       * Format: int32
       * @description The percent retainer tax in the Crystarium.
       */
      Crystarium: number
      /**
       * Format: int32
       * @description The percent retainer tax in Old Sharlayan.
       */
      'Old Sharlayan': number
      /**
       * Format: int32
       * @description The percent retainer tax in Tuliyollal.
       */
      Tuliyollal: number
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData': {
      results?:
        | components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.Result'][]
        | null
      failedItems?: number[] | null
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.AggregatedResult': {
      minListing: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.MinListing']
      medianListing: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.MedianListing']
      recentPurchase: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.RecentPurchase']
      averageSalePrice: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.AverageSalePrice']
      dailySaleVelocity: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.DailySaleVelocity']
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.AverageSalePrice': {
      world: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.AverageSalePrice.Entry']
      dc: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.AverageSalePrice.Entry']
      region: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.AverageSalePrice.Entry']
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.AverageSalePrice.Entry': {
      /** Format: double */
      price: number
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.DailySaleVelocity': {
      world: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.DailySaleVelocity.Entry']
      dc: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.DailySaleVelocity.Entry']
      region: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.DailySaleVelocity.Entry']
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.DailySaleVelocity.Entry': {
      /** Format: double */
      quantity: number
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.MedianListing': {
      world: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.MedianListing.Entry']
      dc: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.MedianListing.Entry']
      region: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.MedianListing.Entry']
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.MedianListing.Entry': {
      /** Format: int32 */
      price: number
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.MinListing': {
      world: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.MinListing.Entry']
      dc: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.MinListing.Entry']
      region: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.MinListing.Entry']
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.MinListing.Entry': {
      /** Format: int32 */
      price: number
      /** Format: int32 */
      worldId?: number | null
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.RecentPurchase': {
      world: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.RecentPurchase.Entry']
      dc: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.RecentPurchase.Entry']
      region: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.RecentPurchase.Entry']
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.RecentPurchase.Entry': {
      /** Format: int32 */
      price: number
      /** Format: int64 */
      timestamp: number
      /** Format: int32 */
      worldId?: number | null
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.Result': {
      /** Format: int32 */
      itemId: number
      nq: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.AggregatedResult']
      hq: components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.AggregatedResult']
      worldUploadTimes?:
        | components['schemas']['Universalis.Application.Views.V2.AggregatedMarketBoardData.WorldUploadTime'][]
        | null
    }
    'Universalis.Application.Views.V2.AggregatedMarketBoardData.WorldUploadTime': {
      /** Format: int32 */
      worldId: number
      /** Format: int64 */
      timestamp: number
    }
    'Universalis.Application.Views.V2.CurrentlyShownMultiViewV2': {
      /** @description The item IDs that were requested. */
      itemIDs?: number[] | null
      /** @description The item data that was requested, keyed on the item ID. */
      items?: {
        [
          key: string
        ]: components['schemas']['Universalis.Application.Views.V1.CurrentlyShownView']
      } | null
      /**
       * Format: int32
       * @description The ID of the world requested, if applicable.
       */
      worldID?: number | null
      /** @description The name of the DC requested, if applicable. */
      dcName?: string | null
      /** @description The name of the region requested, if applicable. */
      regionName?: string | null
      /** @description A list of IDs that could not be resolved to any item data. */
      unresolvedItems?: number[] | null
      /** @description The name of the world requested, if applicable. */
      worldName?: string | null
    }
    'Universalis.Application.Views.V2.HistoryMultiViewV2': {
      /** @description The item IDs that were requested. */
      itemIDs?: number[] | null
      /** @description The item data that was requested, keyed on the item ID. */
      items?: {
        [
          key: string
        ]: components['schemas']['Universalis.Application.Views.V1.HistoryView']
      } | null
      /**
       * Format: int32
       * @description The ID of the world requested, if applicable.
       */
      worldID?: number | null
      /** @description The name of the DC requested, if applicable. */
      dcName?: string | null
      /** @description The name of the region requested, if applicable. */
      regionName?: string | null
      /** @description A list of IDs that could not be resolved to any item data. */
      unresolvedItems?: number[] | null
      /** @description The name of the world requested, if applicable. */
      worldName?: string | null
    }
    'Universalis.Application.Views.V2.UserListView': {
      /** @description The list's ID. */
      id?: string | null
      /** @description The time that this list was created, in milliseconds since the UNIX epoch. */
      created?: string | null
      /** @description The time that this list was updated, in milliseconds since the UNIX epoch. */
      updated?: string | null
      /** @description The name of this list. */
      name?: string | null
      /** @description The IDs of the list items. */
      itemIDs?: number[] | null
    }
    'Universalis.Application.Views.V3.Game.DataCenter': {
      name?: string | null
      region?: string | null
      worlds?: number[] | null
    }
    'Universalis.Application.Views.V3.Game.World': {
      /** Format: int32 */
      id: number
      name?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
